#! /usr/bin/env python

import roslib
roslib.load_manifest('cloudproxy')
import rospy
import cloudproxy.proxy 

if __name__ == "__main__":
    cloudproxy.proxy.start_proxies()
    
    
    
    
    
